### ISSUE TITLE
attr error

### ISSUE THREAD

**Issue by megasss98** [garlfin/dae2scw#2]
everytime i try to convert a dae it says:

Traceback (most recent call last):
  File "C:\Users\Desktop\dae2scw-master\xmlparse.py", line 4, in <module>
    from squaternion import euler2quat, quat2euler, Quaternion
  File "C:\UsersAppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\squaternion\__init__.py", line 7, in <module>
    from squaternion.squaternion import Quaternion
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\squaternion\squaternion.py", line 16, in <module>
    @attr.s(slots=True, frozen=True)
AttributeError: module 'attr' has no attribute 's'

**Comment by garlfin** [comment]
Im pretty sure you have to download an earlier version of the library but I don't know which version

**Comment by MistiDev** [comment]
I did this: "pip install attrs" and "pip install attr.s". But then another mistake appeared.

**Comment by garlfin** [comment]
Theres a specific version of it to install, but I don't know which one
